/*
 * File: app.js
 * Date: Fri Mar 23 2012 14:43:03 GMT-0600 (Mountain Daylight Time)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    name: 'GUI',
	appFolder: 'gui',

    launch: function() {
        Ext.QuickTips.init();

        var cmp1 = Ext.create('GUI.view.mainpanel.MainPanel', {
            renderTo: Ext.getBody()
        });
        cmp1.show();
    }
});
